In [3]:
import numpy as np # for testing purposes later 

In [10]:
class Matrix:

    def __init__(self,matrix): # define init function to establish class variables
        self.matrix = matrix 

    def __add__(self,other): # define add function to + matrices
        if self.matrix.shape != other.shape: # check dimension equality between matrics
            raise NameError('matrices have unequal dimensions') # if not equal, raise error
        result = self.matrix + other # add matrices
        return result

    def __mul__(self,other):# define multiplication function to * matrices
        if self.matrix.shape != other.shape: # check dimension equality between matrics
            raise NameError('matrices have unequal dimensions') # if not equal, raise error
        result = [] # create empty result list that will eventually turn into matrix
        for i in range(len(self.matrix)): # for loop to fill empty matrix with zeros in the same shape as matrix input
            row = []
            for j in range(len(self.matrix)):
                row.append(0)
            result.append(row)
        for i in range(len(self.matrix)): # for loop to add inner products of matrices to earlier matrix
            for j in range(len(other)):
                for k in range(len(other)):
                    result[i][k] += self.matrix[i][j] * other[k][j]
        return result


class Vector(Matrix): 

    def __init__(self,matrix): # define init function to establish inherited class variables
        super().__init__(matrix) # call on super constructor 

    def __pow__(self,other):# define multiplication function to * matrices
        if self.matrix.shape != other.shape: # check dimension equality between matrics
            raise NameError('matrices have unequal dimensions') # if not equal, raise error
        empty_matrix = []
        for i in range(len(self.matrix)): # for loop to create a list of outer product matrix results
            for j in range(len(self.matrix)):
                for k in range(len(other)):
                    for l in range(len(other)):
                        empty_matrix.append(self.matrix[i, j] * other[k, l])
        col_num = self.matrix.shape[0]*2 # multiplied by 2 because outer product matrices are always 2 * input matrix shape
        result = []
        for i in range(col_num): # for loop to convert list above into a matrix
            row = []
            for j in range(col_num):
                row.append(empty_matrix[i * col_num  + j])
            result.append(row)
        return result

# testing
matrix_1 = np.array([[1,2],[3,4]])
matrix_2 = np.array([[5,6],[7,8]]) 

obj = Matrix(matrix_1)
print("addition:",obj.__add__(matrix_2))
print("inner product:",obj.__mul__(matrix_2))

obj = Vector(matrix_1)
print("outer product:",obj.__pow__(matrix_2))
print(type(obj.__pow__(matrix_2)))



addition: [[ 6  8]
 [10 12]]
inner product: [[17, 23], [39, 53]]
outer product: [[5, 6, 7, 8], [10, 12, 14, 16], [15, 18, 21, 24], [20, 24, 28, 32]]
<class 'list'>


## Scratch work

In [4]:
matrix_1 = np.array([[1,2],[3,4]])
matrix_2 = np.array([[5,6],[7,8]])
#print(matrix_1)
#print(matrix_2)

matrix1 = np.matrix(matrix_1)
matrix2 = np.matrix(matrix_2)
#print(matrix1)
#print(matrix2)

print(np.add(matrix1,matrix2))
print(np.inner(matrix1,matrix2))
print(np.outer(matrix1,matrix2))

[[ 6  8]
 [10 12]]
[[17 23]
 [39 53]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]
